// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 scene.glb -t -T 
// Files: scene.glb [13.8MB] > /Users/0sy/workspace/Blocker_Device_Frontend/public/skybox_beach_cala_d_arena/scene-transformed.glb [111.5KB] (99%)
// Author: Isaac Ryan (https://sketchfab.com/djisaacryan)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/skybox-beach-cala-d-arena-d8965f1ea04a4f6da6b8682e7d8f45bc
// Title: Skybox Beach Cala D' Arena
// */

// import * as THREE from 'three'
// import React from 'react'
// import { useGLTF } from '@react-three/drei'
// import { GLTF } from 'three-stdlib'

// type GLTFResult = GLTF & {
//   nodes: {
//     Sphere_Material001_0: THREE.Mesh
//   }
//   materials: {
//     ['Material.001']: THREE.MeshStandardMaterial
//   }
//   animations: GLTFAction[]
// }

// export function Model(props: JSX.IntrinsicElements['group']) {
//   const { nodes, materials } = useGLTF('/skybox_beach_cala_d_arena/scene-transformed.glb') as GLTFResult
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.Sphere_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
//     </group>
//   )
// }

// useGLTF.preload('/skybox_beach_cala_d_arena/scene-transformed.glb')
