/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/american_road_curve_ahead/model.glb -t -T 
Files: public/american_road_curve_ahead/model.glb [48.67MB] > /Users/0sy/workspace/Blocker_Device_Frontend/model-transformed.glb [5.06MB] (90%)
Author: jimbogies (https://sketchfab.com/jimbogies)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/american-road-curve-ahead-337a8213f1b2463baf01973bf9c68f8a
Title: American Road Curve Ahead
*/

import { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { Group } from 'three';

interface ModelProps {
  scale?: number | [number, number, number];
  position?: [number, number, number];
  rotation?: [number, number, number];
}

export function Model({
  scale = 1,
  position = [0, 0, 0],
  rotation = [0, 0, 0]
}: ModelProps) {
  const { scene } = useGLTF('/american_road_curve_ahead/scene.gltf');
  const groupRef = useRef<Group>(null);
  
  useEffect(() => {
    if (!scene) return;

    scene.traverse((obj) => {
      if (obj instanceof THREE.Mesh) {
        obj.castShadow = true;
        obj.receiveShadow = true;
        if (obj.material) {
          obj.material.envMapIntensity = 1;
          obj.material.needsUpdate = true;
        }
      }
    });
  }, [scene]);

  return (
    <primitive 
      ref={groupRef}
      object={scene} 
      scale={scale}
      position={position}
      rotation={rotation}
    />
  );
}

useGLTF.preload('/american_road_curve_ahead/scene.gltf');
